trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master

jobs:
- job: "Build"
  pool:
    vmImage: "windows-2019"
  steps:
  - task: PowerShell@2
    inputs:
      pwsh: true
      filePath: "./tools/build.ps1"
    displayName: "Build NuGet packages"
    env:
      NUGET_PAT: $(nugetPat)
      GITHUB_PAT: $(githubPat)
      DEFAULT_WORKING_DIRECTORY: $(System.DefaultWorkingDirectory)